feat: Add library books management functionality
4csolutions/casecentral pull request #2
Opened 2023-07-03 15:18 UTC by Irfan778899

2023-07-04 07:12 UTC, mujeerhashmi commented on casecentral/case_central/doctype/book/book.py
> +            book_doc['book_image'] = book.get('imageLinks')['thumbnail']
Make sure book.get('imageLinks') is not null

2023-07-06 09:12 UTC, mujeerhashmi requested changes

2023-07-06 09:12 UTC, mujeerhashmi commented on casecentral/case_central/doctype/book/book.js
> +					frm.reload_doc();
Not Required.

2023-07-06 09:19 UTC, Irfan778899 commented on casecentral/case_central/doctype/book/book.json
> +  "item_name",
Added link field to warehouse

2023-07-06 10:57 UTC, Irfan778899 commented on casecentral/case_central/doctype/book/book.js
> +					frm.reload_doc();
removed frm.reload_doc();

2023-07-08 06:56 UTC, mujeerhashmi approved these changes

2023-07-08 06:56 UTC, merged